#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=16
#PBS -l walltime=1:00:00
#PBS -N Lab4_Naive_4096
#PBS -M fuyuan@iupui.edu
#PBS -q gpu
#PBS -V
#PBS -m abe
#PBS -j oe

cd /N/u/fuyuan/BigRed2/hpchw/lab4/naive
# aprun ./naive 4096 1024 2
# aprun ./naive 4096 512 2
# aprun ./naive 4096 256 2
# aprun ./naive 4096 128 2
# aprun ./naive 4096 64 2
aprun ./naive 4096 32 2
aprun ./naive 4096 16 2
aprun ./naive 4096 8 2
aprun ./naive 4096 4 2
aprun ./naive 4096 2 2
aprun ./naive 4096 1 2
